name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Permite que o GitHub Actions faça push de commits

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Garante que todas as tags do Git sejam baixadas

      - name: Configurar identidade do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Gerar nova versão com standard-version
        run: npm run release

      - name: Comitar mudanças no CHANGELOG e package.json
        run: |
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore(release): $(node -p 'require("./package.json").version')" || echo "Nada para commitar"
          git push origin main

      - name: Criar tag e enviar para o repositório
        run: |
          git tag $(node -p "require('./package.json').version")
          git push --tags

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: $(node -p "require('./package.json').version")
          name: 'Release $(node -p ''require("./package.json").version'')'
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
